export const EPISODES_FETCH = 'EPISODES_FETCH';
export const EPISODES_FULFILLED = 'EPISODES_FULFILLED';
export const EPISODES_ERROR = 'EPISODES_ERROR';

export const EPISODE_CREATE = 'EPISODE_CREATE';
export const EPISODE_CREATE_SUCCESS = 'EPISODE_CREATE_SUCCESS';
export const EPISODE_CREATE_ERROR = 'EPISODE_CREATE_ERROR';

export const EPISODE_DELETE = 'EPISODE_DELETE';
export const EPISODE_DELETE_SUCCESS = 'EPISODE_DELETE_SUCCESS';
export const EPISODE_DELETE_ERROR = 'EPISODE_DELETE_ERROR';

export const EPISODE_FETCH = 'EPISODE_FETCH';
export const EPISODE_FULFILLED = 'EPISODE_FULFILLED';
export const EPISODE_ERROR = 'EPISODE_ERROR';
