export const FILM_CREATE = 'FILM_CREATE';
export const FILM_CREATE_SUCCESS = 'FILM_CREATE_SUCCESS';
export const FILM_CREATE_ERROR = 'FILM_CREATE_ERROR';

export const FILM_UPDATE = 'FILM_UPDATE';
export const FILM_UPDATE_SUCCESS = 'FILM_UPDATE_SUCCESS';
export const FILM_UPDATE_ERROR = 'FILM_UPDATE_ERROR';

export const FILM_FETCH = 'FILM_FETCH';
export const FILM_FULFILLED = 'FILM_FULFILLED';
export const FILM_ERROR = 'FILM_ERROR';

export const FILM_RESET = 'FILM_RESET';