export const FILMS_FETCH = 'FILMS_FETCH';
export const FILMS_FULFILLED = 'FILMS_FULFILLED';
export const FILMS_ERROR = 'FILMS_ERROR';

export const FILMS_SORTING = 'FILMS_SORTING';
export const FILMS_SORTED = 'FILMS_SORTED';
export const FILMS_SORTED_FAIL = 'FILMS_SORTED_FAIL';

export const FILM_CREATE = 'FILM_CREATE';
export const FILM_CREATE_SUCCESS = 'FILM_CREATE_SUCCESS';
export const FILM_CREATE_ERROR = 'FILM_CREATE_ERROR';

export const FILM_UPDATE = 'FILM_UPDATE';
export const FILM_UPDATE_SUCCESS = 'FILM_UPDATE_SUCCESS';
export const FILM_UPDATE_ERROR = 'FILM_UPDATE_ERROR';

export const FILM_DELETE = 'FILM_DELETE';
export const FILM_DELETE_SUCCESS = 'FILM_DELETE_SUCCESS';
export const FILM_DELETE_ERROR = 'FILM_DELETE_ERROR';

export const FILM_FETCH = 'FILM_FETCH';
export const FILM_FULFILLED = 'FILM_FULFILLED';
export const FILM_ERROR = 'FILM_ERROR';
