export const LINK_CREATE = 'LINK_CREATE';
export const LINK_CREATE_SUCCESS = 'LINK_CREATE_SUCCESS';
export const LINK_CREATE_ERROR = 'LINK_CREATE_ERROR';

export const LINK_DELETE = 'LINK_DELETE';
export const LINK_DELETE_SUCCESS = 'LINK_DELETE_SUCCESS';
export const LINK_DELETE_ERROR = 'LINK_DELETE_ERROR';
