export const SERIES_FETCH = 'SERIES_FETCH';
export const SERIES_FULFILLED = 'SERIES_FULFILLED';
export const SERIES_ERROR = 'SERIES_ERROR';

export const SERIES_SORTING = 'SERIES_SORTING';
export const SERIES_SORTED = 'SERIES_SORTED';
export const SERIES_SORTED_FAIL = 'SERIES_SORTED_FAIL';