export const SERIE_CREATE = 'SERIE_CREATE';
export const SERIE_CREATE_SUCCESS = 'SERIE_CREATE_SUCCESS';
export const SERIE_CREATE_ERROR = 'SERIE_CREATE_ERROR';

export const SERIE_FETCH = 'SERIE_FETCH';
export const SERIE_FULFILLED = 'SERIE_FULFILLED';
export const SERIE_ERROR = 'SERIE_ERROR';