export const SERIES_FETCH = 'SERIES_FETCH';
export const SERIES_FULFILLED = 'SERIES_FULFILLED';
export const SERIES_ERROR = 'SERIES_ERROR';

export const SERIES_SORTING = 'SERIES_SORTING';
export const SERIES_SORTED = 'SERIES_SORTED';
export const SERIES_SORTED_FAIL = 'SERIES_SORTED_FAIL';

export const SERIE_CREATE = 'SERIE_CREATE';
export const SERIE_CREATE_SUCCESS = 'SERIE_CREATE_SUCCESS';
export const SERIE_CREATE_ERROR = 'SERIE_CREATE_ERROR';

export const SERIE_UPDATE = 'SERIE_UPDATE';
export const SERIE_UPDATE_SUCCESS = 'SERIE_UPDATE_SUCCESS';
export const SERIE_UPDATE_ERROR = 'SERIE_UPDATE_ERROR';

export const SERIE_DELETE = 'SERIE_DELETE';
export const SERIE_DELETE_SUCCESS = 'SERIE_DELETE_SUCCESS';
export const SERIE_DELETE_ERROR = 'SERIE_DELETE_ERROR';

export const SERIE_FETCH = 'SERIE_FETCH';
export const SERIE_FULFILLED = 'SERIE_FULFILLED';
export const SERIE_ERROR = 'SERIE_ERROR';
